### ISSUE TITLE
Transactions conditional tables

### ISSUE THREAD

**Issue by WolnyMikolaj** [ardium-pl/GWW-Legal#13]
Stwórz proszę 6 tabel dla każdej z kategorii transakcji. Kategoria transakcji to zmienna przypisana do każdej transakcji z obiektu kopiowanego z clipboardu. Znajdziesz ją pod kluczem: transactionCategory. 

W każdym obiekcie kopiowanym z clipboardu może być dowolna ilość transakcji z czego każda z innym kodem. Chodzi tutaj o to, żeby zgrupować je razem w tabele i pokazać użytkownikowi tylko te tabele, które faktyczne zwierają w danym momencie jakieś transakcje. 

Fajnie byłoby gdyby użytkownik mógł przełączać się między tabelami przy użyciu sidebara, tak jak w google sheetsach:

![Image](https://github.com/ardium-pl/GWW-Legal/assets/136742392/af37da6b-990a-4bde-a8f9-618503f55de6)

Tabele mają się nazywać: Kategoria A, Kategoria B, ..., Kategoria F. Do każdej z tabel są przypisane są następujące kody:

B: oznaczone kodami 1101 lub 2101
C:  oznaczone kodami 1201–1204 lub 2201–2204
D: oznaczone kodami 1201 lub 2201
E: oznaczone kodami 1401 lub 2401
F: oznaczone kodami 1501 lub 2501
A: jakikolwiek inny kod

**Comment by joker876** [comment]
Chyba najlepiej będzie skorzystać z https://material.angular.io/components/tabs/overview
