### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by WolnyMikolaj** [ardium-pl/GWW-Legal#16]
Dodaj możliwość odświeżania strony w aplikacji do odczytywania orzeczeń. 
* Użytkownik po zadaniu przeczytaniu odpowiedzi na pytania ma mieć możliwość powrotu do karty początkowej (tam gdzie wpisał sygnaturę sprawy), zmiany sygnatury i przejścia całego procesu z zadawaniem pytań od początku.

**Comment by joker876** [comment]
Piękny opis zadania, podoba mi się
