### ISSUE TITLE
Dodatkowe powiązane pytanie

### ISSUE THREAD

**Issue by WolnyMikolaj** [ardium-pl/GWW-Legal#35]
**Paweł:**

* Dodaj do karty, na której prawnik przegląda odpowiedzi na swoje pytanie możliwość dodania dodatkowego pytania 
* Wyobrażałem to sobie jako response do wiadomości na whatsappie 

**Mikołaj:**

* Dodaj do back-endu/zmodyfikuj już istniejący endpoint umożliwiając tym zadawanie dodatkowych pytań do tego, które było już zadane przez użytkownika

**Comment by joker876** [comment]
Endpoint, jaki oczekuję, że będzie zrobiony:

`POST` `/api/nsa/conversation`
Obiekt `body` będzie zawierał tablicę obiektów:
```
{ content: string; type: "user-message" | "system-message" | "response"; }
```
Gdzie każdy obiekt odpowiada jednej wiadomości. Przykładowo:
```
[
  { content: "Your name is Legal Bro. You are...", type: "system-message" },
  { content: "Czy mógłbyś proszę powiedzieć...", type: "user-message" },
  { content: "Naczelny Sąd Administracyjny (NSA) uchylił...", type: "response" },
  { content: "Czy mógłbyś proszę wytłumaczyć...", type: "user-message" },
]
```
Tablica zawsze będzie zawierała obiekt `system-message` pod indeksem 0, a następne obiekty będą zawsze naprzemiennie `user-message` i `response`. Ostatnim obiektem zawsze będzie `user-message`.

Oczekiwanym responsem będzie string zawierający odpowiedź Czatu GPT do zadanej konwersacji.

**Comment by joker876** [comment]
@WolnyMikolaj Jak będziesz miał się zabrać za pracę nad tym zadaniem to zadzwoń do mnie, obgadamy jak by najlepiej zintegrować to z bazą danych.
